apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-keel-bridge
spec:
  selector:
    matchLabels:
      app: discord-keel-bridge
  replicas: 1
  template:
    metadata:
      labels:
        app: discord-keel-bridge
    spec:
      containers:
      - name: discord-keel-bridge
        image: gabisonfire/discord-keel-bridge:1.0
        env:
        - name: DISCORD_BRIDGE_URL
          value: https://discord.com/api/webhooks/123456
        - name: DISCORD_BRIDGE_PORT
          value: 5000
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: discord-keel-bridge
spec:
  selector:
    app: discord-keel-bridge
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000