version: '3.5'
services:
  discord-keel-bridge:
    image: gabisonfire/discord-keel-bridge:1.0
    environment:
      - DISCORD_BRIDGE_URL="https://discord.com/api/webhooks/123456789"
      - DISCORD_BRIDGE_PORT=5000
    ports:
      - 5000:5000
    container_name: discord-keel-bridge
    restart: unless-stopped